#!/usr/bin/env node
/**
 * SheetPunch / CrewClock - Build Script
 * Concatenates modular scripts from js/ in dependency order into app.js
 * for backwards compatibility as a single distribution bundle.
 */

const fs = require('fs');
const path = require('path');

const rootDir = path.resolve(__dirname, '..');
const jsDir = path.join(rootDir, 'js');
const targetFile = path.join(rootDir, 'app.js');

const MODULE_ORDER = [
  'constants.js',
  'state.js',
  'dom.js',
  'utils.js',
  'geo.js',
  'auth.js',
  'sheets.js',
  'queue.js',
  'history.js',
  'team.js',
  'onboarding.js',
  'billing.js',
  'clock.js',
  'main.js'
];

console.log('[Build] Packaging CrewClock modular scripts into app.js...');

let bundledContent = `/**\n * CrewClock / SheetPunch - Application Bundle (Built: ${new Date().toISOString()})\n * DO NOT EDIT THIS FILE DIRECTLY. Edit individual modules in js/ and run npm run build.\n */\n\n`;

for (const moduleFile of MODULE_ORDER) {
  const filePath = path.join(jsDir, moduleFile);
  if (!fs.existsSync(filePath)) {
    console.error(`[Build Error] Missing module: ${moduleFile}`);
    process.exit(1);
  }
  const content = fs.readFileSync(filePath, 'utf8');
  bundledContent += `\n/* ==================== MODULE: js/${moduleFile} ==================== */\n`;
  bundledContent += content;
  bundledContent += '\n';
}

fs.writeFileSync(targetFile, bundledContent, 'utf8');
console.log(`[Build Success] Successfully bundled ${MODULE_ORDER.length} modules into ${targetFile} (${(bundledContent.length / 1024).toFixed(1)} KB)`);
